export const CATEGORY_META = {
  1: { name: "Uncategorized", icon: "💸", color: "bg-slate-500" },
  2: { name: "Food & Drinks", icon: "🍽️", color: "bg-rose-500" },
  3: { name: "Transportation", icon: "🚗", color: "bg-amber-500" },
  4: { name: "Housing", icon: "🏠", color: "bg-emerald-500" },
  5: { name: "Bills", icon: "📄", color: "bg-sky-500" },
  6: { name: "Travel", icon: "✈️", color: "bg-indigo-500" },
  7: { name: "Health", icon: "🏥", color: "bg-red-500" },
  8: { name: "Education", icon: "🎓", color: "bg-violet-500" },
  9: { name: "Shopping", icon: "🛍️", color: "bg-pink-500" },
  10: { name: "Pets", icon: "🐾", color: "bg-orange-500" },
  11: { name: "Sports", icon: "⚽", color: "bg-lime-500" },
  12: { name: "Entertainment", icon: "🎬", color: "bg-fuchsia-500" },
  13: { name: "Investment", icon: "📈", color: "bg-teal-500" },
  14: { name: "Family", icon: "👪", color: "bg-cyan-500" },
  15: { name: "Salary", icon: "💼", color: "bg-blue-600" },
  16: { name: "Bonus", icon: "🎉", color: "bg-amber-400" },
  17: { name: "Business", icon: "🏢", color: "bg-slate-700" },
  18: { name: "Gifts", icon: "🎁", color: "bg-red-400" },
};
